version: "3.8"
services:
  danspro-go-production:
    container_name: ${BACKEND_CONTAINER}
    hostname: ${BACKEND_HOST}
    image: "${BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}"
    restart: always
    environment:
      BACKEND_STAGE: ${BACKEND_STAGE}
    ports:
      - "3001:3001"
    networks:
      - danspro-environment-production

networks:
  danspro-environment-production:
    external: true
    name: danspro-environment-production
