version: "3.8"
services:
  danspro-postgresql-production:
    container_name: ${POSTGRESQL_CONTAINER}
    hostname: ${POSTGRESQL_HOST}
    image: "${POSTGRESQL_IMAGE}:${POSTGRESQL_IMAGE_TAG}"
    restart: always
    environment:
      TZ: ${POSTGRESQL_TIME_ZONE}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - danspro-environment-production

  danspro-redis-production:
    container_name: ${REDIS_CONTAINER}
    hostname: ${REDIS_HOST}
    image: "${REDIS_IMAGE}:${REDIS_IMAGE_TAG}"
    restart: always
    sysctls:
      - net.core.somaxconn=511
    networks:
      - danspro-environment-production

  danspro-pgadmin-production:
    container_name: ${PGADMIN_CONTAINER}
    hostname: ${PGADMIN_HOST}
    image: "${PGADMIN_IMAGE}:${PGADMIN_IMAGE_TAG}"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5432:80"
    networks:
      - danspro-environment-production

  danspro-pgbackups-production:
    container_name: ${PGBACKUPS_CONTAINER}
    hostname: ${PGBACKUPS_HOST}
    image: "${PGBACKUPS_IMAGE}:${PGBACKUPS_IMAGE_TAG}"
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRESQL_HOST}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: "@every 0h10m00s"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 80
    networks:
      - danspro-environment-production
    volumes:
      - ../backups:/backups

networks:
  danspro-environment-production:
    external: true
    name: danspro-environment-production
